[build]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update",
  "apt-get install -y --no-install-recommends pkg-config libssl-dev:$CROSS_DEB_ARCH libxkbcommon-dev:$CROSS_DEB_ARCH libwayland-dev:$CROSS_DEB_ARCH libegl1-mesa-dev:$CROSS_DEB_ARCH libvulkan-dev:$CROSS_DEB_ARCH libx11-dev:$CROSS_DEB_ARCH libxcursor-dev:$CROSS_DEB_ARCH libxrandr-dev:$CROSS_DEB_ARCH libxi-dev:$CROSS_DEB_ARCH libxinerama-dev:$CROSS_DEB_ARCH libasound2-dev:$CROSS_DEB_ARCH libdbus-1-dev:$CROSS_DEB_ARCH libglib2.0-dev:$CROSS_DEB_ARCH libpango1.0-dev:$CROSS_DEB_ARCH libatk1.0-dev:$CROSS_DEB_ARCH libgtk-3-dev:$CROSS_DEB_ARCH"
]
