# Pinel formatting rules

edition = "2021"

max_width = 100
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"

reorder_imports = true
reorder_modules = true

fn_params_layout = "Tall"

match_block_trailing_comma = true
match_arm_leading_pipes = "Never"

# -- misc --
use_field_init_shorthand = true
use_try_shorthand = true
merge_derives = true
chain_width = 80
single_line_if_else_max_width = 0
