name: Release Linux

on:
  workflow_call:
    inputs:
      binary_name:
        required: true
        type: string
      release_tag:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  release-linux:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Build release binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Prepare asset
        shell: bash
        run: |
          cp \
            target/x86_64-unknown-linux-gnu/release/${{ inputs.binary_name }} \
            target/${{ inputs.binary_name }}-linux-x86_64

      - name: Upload asset to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ inputs.binary_name }}-linux-x86_64
          tag_name: ${{ inputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
